version: '3.6'
services:
  server:
    container_name: edtech_csf_server
    build: .
    volumes:
      - $GOPATH:/go
      - .:/go/src/github.com/PaiAkshay998/EdTech_CSF
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      EDTECH_STAGE: "PROD"
  db:
    container_name: edtech_csf_db
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
  phpmyadmin:
    container_name: edtech_csf_pma
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    ports:
      - "9040:80"
    depends_on:
      - db
volumes:
  mysql-data:
    name: edtech-mysql-data
