version: '2'
services:
  server:
    container_name: edtech_csf_server
    build: .
    volumes:
      - $GOPATH:/go
      - ./:/go/src/github.com/PaiAkshay998/EdTech_CSF
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: edtech_csf_db
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    
